import numpy as np 

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = data.data
y = data.target

In [3]:
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1,train_size = 0.8,test_size = 0.2)

train_index,test_index = next(ss.split(X,y))

X_train,X_test=X[train_index],X[test_index]
y_train,y_test = y[train_index],y[test_index]

In [4]:
from sklearn import linear_model
clf = linear_model.LogisticRegression()

In [5]:
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [6]:
clf.score(X_test, y_test)

0.95614035087719296

In [7]:
y_pred = clf.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [9]:
accuracy_score(y_test,y_pred)

0.95614035087719296

In [10]:
cmat = confusion_matrix(y_test, y_pred)
cmat

array([[38,  0],
       [ 5, 71]])

In [12]:
cmat.sum()
cmat.diagonal().sum()
cmat.diagonal().sum() / cmat.sum()


0.95614035087719296

In [13]:
TP = cmat[0,0]
TN = cmat[1,1]
FP = cmat[1,0]
FN = cmat[0,1]
TP, TN, FP, FN

(38, 71, 5, 0)

In [14]:
from sklearn.metrics import classification_report

In [15]:
print(classification_report(y_test, y_pred, digits=4))

             precision    recall  f1-score   support

          0     0.8837    1.0000    0.9383        38
          1     1.0000    0.9342    0.9660        76

avg / total     0.9612    0.9561    0.9567       114



In [16]:
recall_0 = TP / (TP+FN)
recall_0

1.0

In [17]:
precision_0 = TP/(TP+FP)
precision_0

0.88372093023255816

In [18]:
recall_1 = TN / (FP + TN)
# 63 / (63 + 4) class 1 recall, 
#               specificity 特異度

specificity = recall_1
recall_1

0.93421052631578949

In [19]:
precision_1 = TN / (TN + FN)
# = 63/(63+1) class 1 precision

precision_1

1.0

In [20]:
f1_0 = 2 * recall_0 * precision_0 / \
       (recall_0 + precision_0)
# = 2 / (1/recall_0 + 1/precision_0)

f1_0

0.93827160493827166

In [21]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred,pos_label=0),f1_score(y_test, y_pred, pos_label=1)

(0.93827160493827166, 0.9659863945578232)

In [22]:
from sklearn.metrics import fbeta_score
fbeta_score(y_test, y_pred, beta=1, pos_label=0), fbeta_score(y_test, y_pred, beta=1, pos_label=1)

(0.93827160493827166, 0.9659863945578232)

In [23]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred, beta=1)

(array([ 0.88372093,  1.        ]),
 array([ 1.        ,  0.93421053]),
 array([ 0.9382716 ,  0.96598639]),
 array([38, 76]))

In [24]:
from sklearn.datasets import  load_digits
data = load_digits()
X = data.data
y = data.target

In [ ]:
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1,train_size = 0.8,test_)