import numpy as np 

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
X = data.data

In [5]:
dir(data)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [6]:
X.shape

(150, 4)

In [7]:
X[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [8]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
y = data.target

In [10]:
y.shape

(150,)

In [11]:
y[0]

0

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [14]:
from  sklearn import linear_model
clf = linear_model.LogisticRegression()

In [15]:
clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
n_samples = X.shape[0]
n_train = n_samples // 2
n_test = n_samples - n_train

In [18]:
train_index = range(0,n_train)
test_index = range(n_train,n_samples)

In [19]:
np.array(train_index),np.array(test_index)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74]),
 array([ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149]))

In [22]:
X_train ,X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [23]:
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [24]:
print(clf.score(X_train,y_train))

1.0


In [25]:
print(clf.score(X_test,y_test))

0.333333333333


wrong = 0
for i, j in zip(clf.predict(X_test),y_test):
    if i == j:
        print(i,j)
    else:
        print(i,j,"wrong")
        wrong +=1
print(wrong)        

In [27]:
y_train,y_test

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2]))

In [28]:
from sklearn.model_selection import ShuffleSplit

In [30]:
ss = ShuffleSplit(n_splits=1,train_size=0.5,test_size=0.5)


In [31]:
test_index,train_index = next(ss.split(X))

In [32]:
list(test_index),list(train_index)

([71,
  13,
  147,
  82,
  143,
  53,
  118,
  109,
  26,
  42,
  133,
  119,
  79,
  95,
  135,
  148,
  123,
  104,
  81,
  127,
  110,
  146,
  5,
  32,
  106,
  12,
  141,
  117,
  102,
  76,
  64,
  52,
  122,
  15,
  132,
  98,
  1,
  63,
  138,
  18,
  21,
  45,
  17,
  28,
  57,
  124,
  43,
  108,
  46,
  137,
  92,
  8,
  29,
  34,
  2,
  77,
  126,
  78,
  49,
  27,
  37,
  61,
  20,
  51,
  48,
  11,
  83,
  6,
  142,
  56,
  23,
  134,
  101,
  25,
  0],
 [125,
  62,
  55,
  35,
  68,
  54,
  24,
  9,
  50,
  112,
  59,
  131,
  100,
  86,
  144,
  72,
  99,
  75,
  30,
  139,
  74,
  120,
  19,
  96,
  89,
  39,
  3,
  67,
  136,
  88,
  22,
  10,
  33,
  38,
  103,
  70,
  111,
  114,
  41,
  105,
  7,
  107,
  31,
  69,
  40,
  66,
  44,
  73,
  94,
  47,
  85,
  113,
  16,
  80,
  145,
  93,
  128,
  60,
  91,
  149,
  58,
  130,
  97,
  116,
  129,
  4,
  65,
  14,
  140,
  36,
  115,
  121,
  87,
  90,
  84])

In [35]:
X_train ,X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [36]:
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
print(clf.score(X_test,y_test))

0.96


In [38]:
wrong = 0 
for i,j in zip(clf.predict(X_test),y_test):
    if i == j:
        print(i,j)
    else:
        print(i,j,"wrong!!!")
        wrong +=1
        print("間違った回数は"+str(wrong)+"回です")

1 1
0 0
2 2
1 1
2 2
1 1
2 2
2 2
0 0
0 0
1 2 wrong!!!
間違った回数は1回です
1 2 wrong!!!
間違った回数は2回です
1 1
1 1
2 2
2 2
2 2
2 2
1 1
2 2
2 2
2 2
0 0
0 0
2 2
0 0
2 2
2 2
2 2
1 1
1 1
1 1
2 2
0 0
2 2
1 1
0 0
1 1
2 2
0 0
0 0
0 0
0 0
0 0
1 1
2 2
0 0
2 2
0 0
2 2
1 1
0 0
0 0
0 0
0 0
1 1
2 2
1 1
0 0
0 0
0 0
1 1
0 0
1 1
0 0
0 0
2 1 wrong!!!
間違った回数は3回です
0 0
2 2
1 1
0 0
2 2
2 2
0 0
0 0
